apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: mshekhawat
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: manoj7shekhawat/web:v6
        ports:
        - containerPort: 5000
